# Generated by Django 5.1.2 on 2024-12-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/productparams/images/'),
        ),
    ]
