# Generated by Django 5.1.2 on 2024-12-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productparams_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productparams',
            name='image',
        ),
    ]
