# Generated by Django 5.1.2 on 2024-12-26 07:48

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/products/thumbnails'),
        ),
    ]
