# Generated by Django 5.1.2 on 2024-12-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
