# Generated by Django 5.1.4 on 2025-01-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product')]},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
