# Generated by Django 5.1.2 on 2024-12-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_store_product_storeid'),
        ('orders', '0002_cart_product_cartitem_product_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='height',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Height in cm', max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='length',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Length in cm', max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='store_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='width',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Width in cm', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='height',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
